### ISSUE TITLE
Compile error #include "If_DBR.h" not found

### ISSUE THREAD

**Issue by amnotafraid** [dynamsoftlabs/raspberry-pi-nodejs-barcode-reader-#1]
I am trying to configure a Raspberry Pi to interface with a camera, get a picture of a barcode, and tell me what the barcode is.  So far, I haven't been able to compile and run the code to even try it.

## Questions
- So, can I use this code on Raspberry Pi to accomplish my objective?
- If so, how can I configure the Raspberry Pi?
- Do I need to install **both** the [SDK](http://www.dynamsoft.com/Downloads/XTRKJFPOUMIDSCGQBI_RaspberryPi_DBR.aspx) and [raspberry-pi-nodejs-barcode-reader-](https://github.com/dynamsoftlabs/raspberry-pi-nodejs-barcode-reader-)?  
- There are conflicting instuctions for setting this up.  Which one should I use:
     - [http://www.codepool.biz/nodejs-barcode-scanner-camera-raspberrypi.html](http://www.codepool.biz/nodejs-barcode-scanner-camera-raspberrypi.html)
     - [http://www.codepool.biz/raspberry-pi-nodejs-barcode-reader.html
](http://www.codepool.biz/raspberry-pi-nodejs-barcode-reader.html)
- And finally, how can I build the code?

## Basic compile error
I am successfully able to execute `node-gyp configure`, but I have trouble building the code.  `node-gyp build` gives me this:
```
make: Entering directory '/srv/raspberry-pi-nodejs-barcode-reader-/build'
  CXX(target) Release/obj.target/dbr/dbr.o
../dbr.cc:5:20: fatal error: If_DBR.h: No such file or directory
 #include "If_DBR.h"
                    ^
compilation terminated.
dbr.target.mk:94: recipe for target 'Release/obj.target/dbr/dbr.o' failed
```

## Server versions
```
cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
### Tool Versions
```
npm -v
5.3.0
nvm --version
0.31.7
node -v
v6.10.0
git --version
git version 2.1.4
python -V
Python 2.7.9
make -v
GNU Make 4.0
gcc -v
uname -m
armv6l
...
gcc version 4.9.2 (Raspbian 4.9.2-10)
```
## Server setup

When I started out, I did this and there didn't seem to be any errors:
```
sudo apt-get update
sudo apt-get upgrade
```
I used .nvm for node installation:
```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.7/install.sh | bash
source ~/.bashrc
nvm install v6.10.0
npm install npm@latest -g
```
I downloaded the SDK from [here](http://www.dynamsoft.com/Downloads/XTRKJFPOUMIDSCGQBI_RaspberryPi_DBR.aspx), unzipped it into `/home/pi/dbr-V4.2.0-linux-armv71` and made a symlink:
```
sudo ln -s /home/pi/dbr-V4.2.0-linux-armv71/lib/libDynamsoftBarcodeReader.so /usr/lib/libDynamsoftBarcodeReader.so
```
I did
```
npm install -g node-gyp
```
In the `/srv` directory, I cloned this repository:
```
git clone https://github.com/dynamsoftlabs/raspberry-pi-nodejs-barcode-reader-.git
```
Then, in /srv/raspberry-pi-nodejs-barcode-reader-:
```
npm install
node-gyp configure
```
These seemed to go all right.  With `node-gyp build`, I got these errors:
```
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@6.10.0 | linux | arm
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/srv/raspberry-pi-nodejs-barcode-reader-/build'
  CXX(target) Release/obj.target/dbr/dbr.o
../dbr.cc:5:20: fatal error: If_DBR.h: No such file or directory
 #include "If_DBR.h"
                    ^
compilation terminated.
dbr.target.mk:94: recipe for target 'Release/obj.target/dbr/dbr.o' failed
make: *** [Release/obj.target/dbr/dbr.o] Error 1
make: Leaving directory '/srv/raspberry-pi-nodejs-barcode-reader-/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v6.10.0/lib/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.9.35+
gyp ERR! command "/root/.nvm/versions/node/v6.10.0/bin/node" "/root/.nvm/versions/node/v6.10.0/bin/node-gyp" "build"
gyp ERR! cwd /srv/raspberry-pi-nodejs-barcode-reader-
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

**Comment by yushulx** [comment]
> ../dbr.cc:5:20: fatal error: If_DBR.h: No such file or directory
>  #include "If_DBR.h

Have you checked the file path? Open **binding.gyp** and edit the include path:

```
'include_dirs': [
                "/home/pi/dbr-V4.2.0-linux-armv7l/include"
            ]
```

**Comment by amnotafraid** [comment]
Thank you for your response!  I know that I wrote a lot of stuff.  The **binding.gyp** file looks correct to me.  Here is the directory where the includes are:
```
/home/pi/dbr-V4.2.0-linux-armv71/include
```
This is what the binding.gyp looks like:
```
{
  "targets": [
    {
      'target_name': "dbr",
      'sources': [ "dbr.cc" ],
      'conditions': [
          ['OS=="linux"', {
            'defines': [
              'LINUX_DBR',
            ],
            'include_dirs': [
                "/home/pi/dbr-V4.2.0-linux-armv7l/include"
            ],
            'libraries': [
                "-lDynamsoftBarcodeReader", "-L/home/pi/dbr-V4.2.0-linux-armv7l/lib"
            ]
          }]
      ]
    }
  ]
}
```
I finally got it to compile by copying the files from `/home/pi/dbr-V4.2.0-linux-armv71/include` into the root directory of the github clone.  Goofy, huh?  It must be how I have the Raspberry Pi set up.
